services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: appointment_db
      MYSQL_USER: appointment_user
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/mysql
    networks:
      - appointment-network

  mysql-client:
    image: phpmyadmin
    container_name: mysql-client
    environment:
      PMA_HOST: mysql-server
      PMA_USER: appointment_user
      PMA_PASSWORD: 12345
    ports:
      - "8080:80"
    networks:
      - appointment-network

networks:
  appointment-network:
    driver: bridge
    name: appointment-network
