post http://localhost:3000/api/v1/appointment
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJKYXZpZXIgR29tZXoiLCJpYXQiOjE3ODA5NjQyOTYsImV4cCI6MTc4MDk2Nzg5Nn0.fq8N-4SnUguAy_96cLYGzMlxxJXO6op1OTSjXkQwzIs

{
   "slotId": 3000,
   "patientId": 345
}

###
post http://localhost:3010/api/v1/appointment
content-type: application/json

{
   "slotId": 2000,
   "patientId": 345,
   "countryISO": "CL"
}