post http://localhost:3000/api/v1/appointment
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJKYXZpZXIgR29tZXoiLCJpYXQiOjE3ODA3MDU2ODAsImV4cCI6MTc4MDcwOTI4MH0.KtOTDmaBMn_grNEk2305rIvpkpWPwTQBrip_h2bG80A

{
   "slotId": 3000,
   "patientId": 345
}

###
post http://localhost:3010/api/v1/appointment
content-type: application/json

{
   "slotId": 2000,
   "patientId": 345,
   "countryISO": "CL"
}