post http://localhost:3000/api/v1/patient
content-type: application/json

{
   "name": "Javier",
   "lastname": "Gomez",
   "email": "javier.gomez@email.com",
   "countryISO": "CL",
   "age": 30,
   "password": "password123"
}

### Login
post http://localhost:3070/api/v1/patient/login
content-type: application/json

{
   "email": "javier.gomez@email.com",
   "password": "password123"
}